HEROES = [
'',
'[](/hero-antimage "Anti-Mage")',
'[](/hero-axe "Axe")',
'[](/hero-bane "Bane")',
'[](/hero-bloodseeker "Bloodseeker")',
'[](/hero-crystalmaiden "Crystal Maiden")',
'[](/hero-drowranger "Drow Ranger")',
'[](/hero-earthshaker "Earthshaker")',
'[](/hero-juggernaut "Juggernaut")',
'[](/hero-mirana "Mirana")',
'[](/hero-morphling "Morphling")',
'[](/hero-shadowfiend "Shadow Fiend")',
'[](/hero-phantomlancer "Phantom Lancer")',
'[](/hero-puck "Puck")',
'[](/hero-pudge "Pudge")',
'[](/hero-razor "Razor")',
'[](/hero-sandking "Sand King")',
'[](/hero-stormspirit "Storm Spirit")',
'[](/hero-sven "Sven")',
'[](/hero-tiny "Tiny")',
'[](/hero-vengefulspirit "Vengeful Spirit")',
'[](/hero-windranger "Windranger")',
'[](/hero-zeus "Zeus")',
'[](/hero-kunkka "Kunkka")',
'24',
'[](/hero-lina "Lina")',
'[](/hero-lion "Lion")',
'[](/hero-shadowshaman "Shadow Shaman")',
'[](/hero-slardar "Slardar")',
'[](/hero-tidehunter "Tidehunter")',
'[](/hero-witchdoctor "Witch Doctor")',
'[](/hero-lich "Lich")',
'[](/hero-riki "Riki")',
'[](/hero-enigma "Enigma")',
'[](/hero-tinker "Tinker")',
'[](/hero-sniper "Sniper")',
'[](/hero-necrophos "Necrophos")',
'[](/hero-warlock "Warlock")',
'[](/hero-beastmaster "Beastmaster")',
'[](/hero-queenofpain "Queen of Pain")',
'[](/hero-venomancer "Venomancer")',
'[](/hero-facelessvoid "Faceless Void")',
'[](/hero-wraithking "Wraith King")',
'[](/hero-deathprophet "Death Prophet")',
'[](/hero-phantomassassin "Phantom Assassin")',
'[](/hero-pugna "Pugna")',
'[](/hero-templarassassin "Templar Assassin")',
'[](/hero-viper "Viper")',
'[](/hero-luna "Luna")',
'[](/hero-dragonknight "Dragon Knight")',
'[](/hero-dazzle "Dazzle")',
'[](/hero-clockwerk "Clockwerk")',
'[](/hero-leshrac "Leshrac")',
'[](/hero-naturesprophet "Nature\'s Prophet")',
'[](/hero-lifestealer "Lifestealer")',
'[](/hero-darkseer "Dark Seer")',
'[](/hero-clinkz "Clinkz")',
'[](/hero-omniknight "Omniknight")',
'[](/hero-enchantress "Enchantress")',
'[](/hero-huskar "Huskar")',
'[](/hero-nightstalker "Night Stalker")',
'[](/hero-broodmother "Broodmother")',
'[](/hero-bountyhunter "Bounty Hunter")',
'[](/hero-weaver "Weaver")',
'[](/hero-jakiro "Jakiro")',
'[](/hero-batrider "Batrider")',
'[](/hero-chen "Chen")',
'[](/hero-spectre "Spectre")',
'[](/hero-ancientapparition "Ancient Apparition")',
'[](/hero-doom "Doom")',
'[](/hero-ursa "Ursa")',
'[](/hero-spiritbreaker "Spirit Breaker")',
'[](/hero-gyrocopter "Gyrocopter")',
'[](/hero-alchemist "Alchemist")',
'[](/hero-invoker "Invoker")',
'[](/hero-silencer "Silencer")',
'[](/hero-outworlddevourer "Outworld Devourer")',
'[](/hero-lycan "Lycan")',
'[](/hero-brewmaster "Brewmaster")',
'[](/hero-shadowdemon "Shadow Demon")',
'[](/hero-lonedruid "Lone Druid")',
'[](/hero-chaosknight "Chaos Knight")',
'[](/hero-meepo "Meepo")',
'[](/hero-treantprotector "Treant Protector")',
'[](/hero-ogremagi "Ogre Magi")',
'[](/hero-undying "Undying")',
'[](/hero-rubick "Rubick")',
'[](/hero-disruptor "Disruptor")',
'[](/hero-nyxassassin "Nyx Assassin")',
'[](/hero-nagasiren "Naga Siren")',
'[](/hero-keeperofthelight "Keeper of the Light")',
'[](/hero-io "Io")',
'[](/hero-visage "Visage")',
'[](/hero-slark "Slark")',
'[](/hero-medusa "Medusa")',
'[](/hero-trollwarlord "Troll Warlord")',
'[](/hero-centaurwarrunner "Centaur Warrunner")',
'[](/hero-magnus "Magnus")',
'[](/hero-timbersaw "Timbersaw")',
'[](/hero-bristleback "Bristleback")',
'[](/hero-tusk "Tusk")',
'[](/hero-skywrathmage "Skywrath Mage")',
'[](/hero-abaddon "Abaddon")',
'[](/hero-eldertitan "Elder Titan")',
'[](/hero-legioncommander "Legion Commander")',
'[](/hero-techies "Techies")',
'[](/hero-emberspirit "Ember Spirit")',
'[](/hero-earthspirit "Earth Spirit")',
'[](/hero-abyssalunderlord "Underlord")',
'[](/hero-terrorblade "Terrorblade")',
'[](/hero-phoenix "Phoenix")',
'[](/hero-oracle "Oracle")',
'[](/hero-winterwyvern "Winter Wyvern")',
'[](/hero-arcwarden "Arc Warden")',
'[](/hero-monkeyking "Monkey King")'
]
